# Generated by Django 5.2.1 on 2025-05-31 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Статус выполнения задачи')),
                ('color_tag', models.CharField(blank=True, help_text='Цвет в формате #000000', max_length=7, null=True, verbose_name='Цветовой тэг (HEX)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Статус выполнения задачи',
                'verbose_name_plural': 'Статусы выполнения задач',
            },
        ),
        migrations.CreateModel(
            name='WorkDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Направление')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Направление работы',
                'verbose_name_plural': 'Направления работы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('description', models.TextField(max_length=200, verbose_name='Описание задачи')),
                ('deadline', models.DateField(verbose_name='Дедлайн')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Команда')),
                ('status', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.taskstatus', verbose_name='Статус задачи')),
                ('direction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.workdirection', verbose_name='Направление работы')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title', 'direction', 'deadline', 'status'], name='tasks_task_title_db0c8a_idx')],
            },
        ),
    ]
