# Generated by Django 5.2.1 on 2025-05-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('Ожидает выполнения', 'Ожидает выполнения'), ('В работе', 'В работе'), ('Выполнена', 'Выполнена')], default='Ожидает выполнения', verbose_name='Статус задачи'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название задачи'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['title'], name='tasks_tasks_title_cc5198_idx'),
        ),
    ]
