# Generated by Django 5.2.1 on 2025-05-30 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_status_alter_tasks_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Статус выполнения задачи')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Статус выполнения задачи',
                'verbose_name_plural': 'Статусы выполнения задач',
            },
        ),
        migrations.CreateModel(
            name='WorkDirections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Направление')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Направление работы',
                'verbose_name_plural': 'Направления работы',
            },
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='dedline',
            new_name='deadline',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.taskstatus', verbose_name='Статус задачи'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='direction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.workdirections', verbose_name='Направление работы'),
        ),
    ]
