# Generated by Django 5.2.1 on 2025-05-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskstatus_workdirections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='color_tag',
            field=models.CharField(blank=True, help_text='Цвет в формате #000000', max_length=7, null=True, verbose_name='Цветовой тэг (HEX)'),
        ),
    ]
