# Generated by Django 5.2.1 on 2025-05-30 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskstatus_color_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='status',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('description', models.TextField(max_length=200, verbose_name='Описание задачи')),
                ('deadline', models.DateField(verbose_name='Дедлайн')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('direction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.workdirections', verbose_name='Направление работы')),
                ('status', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.taskstatus', verbose_name='Статус задачи')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
    ]
