# Generated by Django 5.2.1 on 2025-05-30 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_tasks_direction_remove_tasks_status_task'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Команда'),
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['title'], name='tasks_task_title_6b13c2_idx'),
        ),
    ]
