# Generated by Django 5.2.1 on 2025-05-30 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_team_delete_tasks_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkDirections',
            new_name='WorkDirection',
        ),
    ]
