# Generated by Django 5.2.1 on 2025-05-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_rename_workdirections_workdirection'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_title_6b13c2_idx',
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['title', 'direction', 'deadline', 'status'], name='tasks_task_title_db0c8a_idx'),
        ),
    ]
