# Generated by Django 5.2.1 on 2025-05-31 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_worker_groups_alter_worker_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='teams.team', verbose_name='Команда'),
        ),
    ]
